ecommerce-masonry/ecommerce-masonry/Controllers/CartController.cs
using Braintree;
using Masonry_Data_Access;
using Masonry_Data_Access.Repository.IRepository;
using Masonry_Models;
using Masonry_Models.ViewModels;
using Masonry_Utility;
using Masonry_Utility.BrainTree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace ecommerce_masonry.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        //private readonly ApplicationDbContext _db;
        private readonly IProductRepository _prodRepo;
        private readonly IApplicationUserRepository _applicationUserRepo;
        private readonly IInquiryHeaderRepository _inquiryHeaderRepo;
        private readonly IInquiryDetailsRepository _inquiryDetailsRepo;
        private readonly IOrderDetailRepository _orderDetailRepo;
        private readonly IOrderHeaderRepository _orderHeaderRepo;
        private readonly IBrainTreeGate _brain;


        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;
        [BindProperty]
        public ProductUserViewModel ProductUserViewModel { get; set; }
        public CartController(IProductRepository productRepo, IApplicationUserRepository applicationUserRepo, IInquiryHeaderRepository inquiryHeaderRepo, IInquiryDetailsRepository inquiryDetailsRepo, IWebHostEnvironment webHostEnvironment, IEmailSender emailSender, IOrderDetailRepository orderDetailRepo, IOrderHeaderRepository orderHeaderRepo, IBrainTreeGate brain)
        {
            //_db = db;
            _prodRepo = productRepo;
            _applicationUserRepo = applicationUserRepo;
            _inquiryHeaderRepo = inquiryHeaderRepo;
            _inquiryDetailsRepo = inquiryDetailsRepo;

            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
            _orderDetailRepo = orderDetailRepo;
            _orderHeaderRepo = orderHeaderRepo;
            _brain = brain;
        }
        public IActionResult Index()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart) !=null && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart).Count() > 0)
            {// Session exists and we can retrive all of the products
                shoppingCartList = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart).ToList();
                //shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WebConstance.SessionCart); // Convert to list as you retrive or as above, after we retribe is the same!!
            }

            List<int> prodInCart = shoppingCartList.Select(i => i.ProductId).ToList(); // Here we find out all distinct products in cart using projections  .Select(i => i.ProductId)
            IEnumerable<Product> productListTemp = _prodRepo.GetAll(u => prodInCart.Contains(u.Id));
            IList<Product> productList = new List<Product>();
            //IEnumerable<Product> productList = _db.Product.Where(u => prodInCart.Contains(u.Id));

            foreach (var item in shoppingCartList)
            {
                Product prodTemp = productListTemp.FirstOrDefault(u => u.Id == item.ProductId);
                prodTemp.TempSqft = item.Sqft;
                productList.Add(prodTemp);
            }

            return View(productList);
        }

        public IActionResult Remove(int id)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart) != null && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart).Count() > 0)
            {// Session exists and we can retrive all of the products
                shoppingCartList = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart).ToList();
                //shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WebConstance.SessionCart); // Convert to list as you retrive or as above, after we retribe is the same!!
            }

            shoppingCartList.Remove(shoppingCartList.FirstOrDefault(u=>u.ProductId == id)); // First or default to retrive object based on ID

            HttpContext.Session.Set(WebConstance.SessionCart, shoppingCartList);
            TempData[WebConstance.Success] = "Successfully removed from cart!";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost(IEnumerable<Product> ProdList)
        {

            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            foreach (Product item in ProdList)
            {
                shoppingCartList.Add(new ShoppingCart { ProductId = item.Id, Sqft = item.TempSqft });
            }
            HttpContext.Session.Set(WebConstance.SessionCart, shoppingCartList);
            return RedirectToAction(nameof(Summary));
        }
        
        public IActionResult Summary()
        {
            ApplicationUser applicationUser;

            if (User.IsInRole(WebConstance.AdminRole))
            {
                if (HttpContext.Session.Get<int>(WebConstance.SessionInquiryId) != 0)
                {
                    //cart has been loaded using an imnquiry
                    InquiryHeader inquiryHeader = _inquiryHeaderRepo.FirstOrDefault(u => u.Id == HttpContext.Session.Get<int>(WebConstance.SessionInquiryId)); // retrive inquiry from database

                    applicationUser = new ApplicationUser()
                    {
                        Email = inquiryHeader.Email,
                        FullUserName = inquiryHeader.FullName,
                        PhoneNumber = inquiryHeader.PhoneNumber

                    };
                }
                else
                {
                    applicationUser = new ApplicationUser(); 
                    // This means user is admin user and is placing order for a costumert hat walked in store 
                }
                // Here we get client token.
                // Only if the user is admin user.
                var gateway = _brain.GetGateWay(); // we call getgateway because if it does not exist it is created remember?
                var clientToken = gateway.ClientToken.Generate(); // This is provided by braintree team, and gets us the client token.
                ViewBag.ClientToken = clientToken; // I don't like viewbag, but we only need it in this page. Usually I use VewModels.
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                //var userId = User.FindFirstValue(ClaimTypes.Name);
                applicationUser = _applicationUserRepo.FirstOrDefault(u=>u.Id == claim.Value);
            }



            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart) != null && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart).Count() > 0)
            {// Session exists and we can retrive all of the products
                shoppingCartList = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WebConstance.SessionCart).ToList();
                //shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WebConstance.SessionCart); // Convert to list as you retrive or as above, after we retribe is the same!!
            }

            List<int> prodInCart = shoppingCartList.Select(i => i.ProductId).ToList(); // Here we find out all distinct products in cart using projections  .Select(i => i.ProductId)
            IEnumerable<Product> productList = _prodRepo.GetAll(u => prodInCart.Contains(u.Id));

            ProductUserViewModel = new ProductUserViewModel()
            {
                ApplicationUser = applicationUser,
                //ProductList = productList.ToList()
            };

            //    We do not have sqft inside productList, but we do inside shoppingCartList
            //    So foreach item in it,  we retrive sqft
            foreach (var item in shoppingCartList)
            {
                Product prodTemp = _prodRepo.FirstOrDefault(u => u.Id == item.ProductId); // We retrive product
                prodTemp.TempSqft = item.Sqft; // we set product sqft here
                ProductUserViewModel.ProductList.Add(prodTemp); // We add the product to the list here.

            }

            return View(ProductUserViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(IFormCollection collection, ProductUserViewModel ProductUserViewModel)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            // Below we separare the logic inside the SummaryPost, for both Order and Inquiry cases, for admins and users respectively
            if (User.IsInRole(WebConstance.AdminRole))
            { // This means we need to create an order
                double orderTotal = 0.0;

                foreach (var item in ProductUserViewModel.ProductList)
                {
                    orderTotal = item.Price * item.TempSqft; // we calculate total price here
                }
                OrderHeader orderHeader = new OrderHeader()
                {
                    CreatedByUserId = claim.Value,

ecommerce-masonry/ecommerce-masonry/Controllers/InquiryController.cs
using Masonry_Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Masonry_Utility;
using Masonry_Data_Access;
using Masonry_Data_Access.Repository.IRepository;
using Masonry_Models.ViewModels;

namespace ecommerce_masonry.Controllers
{
    [Authorize(Roles = WebConstance.AdminRole)] // We add this so that only admin can have access to inquiry control. Comment this to find more!
    public class InquiryController : Controller
    {
    private readonly IInquiryHeaderRepository _inquiryHeaderRepo;
    private readonly IInquiryDetailsRepository _inquiryDetailsRepo;

    [BindProperty]
    public InquiryViewModel InquiryViewModel { get; set; }

        public InquiryController(IInquiryHeaderRepository inquiryHeaderRepository, IInquiryDetailsRepository inquiryDetailsRepository)
        {
            _inquiryHeaderRepo = inquiryHeaderRepository; // We add dependency injection for header and detail
            _inquiryDetailsRepo = inquiryDetailsRepository;
        }

        public IActionResult Index()
        {
            return View();
        }        
        public IActionResult Details(int id)
        {
            InquiryViewModel = new InquiryViewModel()
            {
                InquiryHeader = _inquiryHeaderRepo.FirstOrDefault(u => u.Id == id),
                InquiryDetails = _inquiryDetailsRepo.GetAll(u => u.InquiryHeaderId == id,includeProperties: "Product")
            };
            return View(InquiryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            InquiryViewModel.InquiryDetails = _inquiryDetailsRepo.GetAll(u => u.InquiryHeaderId == InquiryViewModel.InquiryHeader.Id);

            foreach (var item in InquiryViewModel.InquiryDetails)
            {
                ShoppingCart shoppingCart = new ShoppingCart()
                {
                    ProductId = item.ProductId
                };
                shoppingCartList.Add(shoppingCart);
            }
                HttpContext.Session.Clear();
                HttpContext.Session.Set(WebConstance.SessionCart, shoppingCartList);
                HttpContext.Session.Set(WebConstance.SessionInquiryId, InquiryViewModel.InquiryHeader.Id);
                // If above line is zero session was set normally in homepage. If not, it was set using inquiry button.
                TempData[WebConstance.Success] = "Successfully converted to cart!";
            return RedirectToAction("Index", "Cart"); // Redirect to Index action inside cart controller

        }

            [HttpPost]
            public IActionResult Delete()
            {
                InquiryHeader inquiryHeader = _inquiryHeaderRepo.FirstOrDefault(u => u.Id == InquiryViewModel.InquiryHeader.Id);
                IEnumerable<InquiryDetails> inquiryDetails = _inquiryDetailsRepo.GetAll(u => u.InquiryHeaderId == InquiryViewModel.InquiryHeader.Id);

            _inquiryHeaderRepo.Remove(inquiryHeader);
            _inquiryDetailsRepo.RemoveRange(inquiryDetails); // I had to add a RemoveRange on IRepository for this...
            _inquiryDetailsRepo.Save();
            _inquiryHeaderRepo.Save();

                TempData[WebConstance.Success] = "Successfully deleted inquiry list!";
            return RedirectToAction(nameof(Index)); ;
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetInquiryList()
        {
            return Json(new { data = _inquiryHeaderRepo.GetAll() });
        }
        #endregion
    }
}

ecommerce-masonry/ecommerce-masonry/Controllers/TransportCategoryController.cs
using Masonry_Data_Access;
using Masonry_Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ecommerce_masonry.Controllers
{
    public class TransportCategoryController : Controller

    {
        private readonly ApplicationDbContext _db; // Here we save an instance of Dbontext that was passed on constructor after dependency injection created it 

        public TransportCategoryController(ApplicationDbContext db) // We populate the property above using dependency injection
        {
            // This object will have an instance of the dbcontext that dependency injection creates and passes to us through the constructor.
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<TransportCategory> objList = _db.TransportCategory;

            //System.Diagnostics.Debug.WriteLine("Output is: " + objList); // Use this for debug purposes <3
            // Source: https://www.youtube.com/watch?v=IpGNe3jLxQo&t=84s

            return View(objList);
        }

        // GET FOR CREATE
        public IActionResult Create()
        {
            return View(); // Here we display empty box to enter name for new transport category to create
        }

        // POST FOR CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TransportCategory obj)
        {
            if (ModelState.IsValid)
            {
                _db.TransportCategory.Add(obj);
                _db.SaveChanges();

                return RedirectToAction("Index"); // RedirectToAction redirects us to the index in this controler, so no need to define the name of the controller here.
            }
            return View(obj);
        }
    }
}

ecommerce-masonry/ecommerce-masonry/Views/Shared/_Favicons.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

ecommerce-masonry/ecommerce-masonry/Views/Shared/_IndividualProductCard.cshtml
@model Masonry_Models.Product

@*Bootstrao styling template added from resources*@

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.CategoryName.Replace(" ","_")">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}", @Model.Price)</span> / sqft</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@Masonry_Utility.WebConstance.imagePath@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Category.CategoryName</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue">@Model.ApplicationType.CategoryName</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesc</p>
            </div>
            <div class="col-12 p-1">
                <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

ecommerce-masonry/ecommerce-masonry/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using Masonry_Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ecommerce_masonry</title>

    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/fontawesomestuff/css/all.css" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <!-- include summernote css -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

    @Html.Partial("_Favicons")
    @* Sources: https://realfavicongenerator.net/ and https://icons8.com/icons/set/rock-64x64 *@
    @* How to: https://andrewlock.net/adding-favicons-to-your-asp-net-core-website-with-realfavicongenerator/ *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/icons8-moai-64.png" width="40%" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />


                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
        </li>*@
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="TransportCategory" asp-action="Index">Transport Type</a>
        </li>*@
                        @if (User.IsInRole(WebConstance.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                    Order/Inquiry Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Inquiry" asp-action="Index">Inquiry</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="Index">Inquiry Order</a></li>
                                </ul>
                            </li>
                        }
                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstance.SessionCart) != null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class=" nav-link">
                                    @{ var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstance.SessionCart).Count; }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a> }
                            else
                            {
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)

                                </a>
                            }
                            @* https://www.reddit.com/r/csharp/comments/gukq4e/no_service_for_type/ I registered the interface, not the concrete type. *@
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />@*This is how we fetch from the notifications partialview!!!*@
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container text-white-50">
            &copy; 2021 - ecommerce_masonry - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- include summernote js -->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
<ejs-scripts></ejs-scripts>
</body>
</html>

ecommerce-masonry/ecommerce-masonry/Views/Shared/_Notifications.cshtml
@using Masonry_Utility@*To use web constance*@

@if (TempData[WebConstance.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData[WebConstance.Success]')
    </script>

}

@if (TempData[WebConstance.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.error('@TempData[WebConstance.Error]')
    </script>

}