ecommerce-masonry/ecommerce-masonry/Controllers/ApplicationTypeController.cs
using Masonry_Data_Access.Repository.IRepository;
using Masonry_Models;
using Masonry_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ecommerce_masonry.Controllers
{
    [Authorize(Roles = WebConstance.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _appType;

        public ApplicationTypeController(IApplicationTypeRepository appType) // We populate the property above using dependency injection
        {
            // This object will have an instance of the dbcontext that dependency injection creates and passes to us through the constructor.
            _appType = appType;
        }

        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objectList = _appType.GetAll();
            return View(objectList);
        }

        // GET FOR CREATE
        public IActionResult Create()
        {

            return View();
        }
        // POST FOR CREATE
        [HttpPost] // We define this as a post action method, with this attribute
        [ValidateAntiForgeryToken] // This is for validation purposes - built in mechanic
        public IActionResult Create(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _appType.Add(obj);
                _appType.Save();
                TempData[WebConstance.Success] = "Application created successfully!";
                return RedirectToAction("Index"); // We're in the same controller we don't need to define controller name here
            }
                TempData[WebConstance.Error] = "Error while creating application!";
            return View(obj);
        }

        // GET FOR EDIT
        public IActionResult Edit(int? id) // Receive id from asp-route on View Category Index
        {
            if (id == null || id == 0) // Check these invalid conditions, we don't want them
            {
                return NotFound();
            }

            var obj = _appType.Find(id.GetValueOrDefault()); // We retrieve category from the database if valid.

            if (obj == null) // Check this invalid condition, we don't want it. (If not found)
            {
                return NotFound();
            }
            return View(obj); // If we found the record, pass it to the view so we can display it!!!
        }

        // POST FOR EDIT
        [HttpPost] // We define this as a post action method, with this attribute
        [ValidateAntiForgeryToken] // This is for validation purposes - built in mechanic
        public IActionResult Edit(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _appType.Update(obj); // So this Updates the database.
                _appType.Save(); // But this is what actually saves it?!?
                TempData[WebConstance.Success] = "Updated successfully!";
                return RedirectToAction("Index"); // We're in the same controller we don't need to define controller name here
            }
                TempData[WebConstance.Error] = "Error while updating";
            return View(obj);
        }

        // GET FOR DELETE
        public IActionResult Delete(int? id) // Receive id from asp-route on View Category Index
        {
            if (id == null || id == 0) // Check these invalid conditions, we don't want them
            {
                return NotFound();
            }

            var obj = _appType.Find(id.GetValueOrDefault()); // We retrieve category from the database if valid.

            if (obj == null) // Check this invalid condition, we don't want it. (If not found)
            {
                return NotFound();
            }
            return View(obj); // If we found the record, pass it to the view so we can display it!!!
        }

        // POST FOR DELETE
        [HttpPost] // We define this as a post action method, with this attribute
        [ValidateAntiForgeryToken] // This is for validation purposes - built in mechanic
        public IActionResult DeletePost(int? id)
        {
            var obj = _appType.Find(id.GetValueOrDefault()); // We retrieve category from the database if valid.
            if (obj == null)
            {
                TempData[WebConstance.Error] = "Error while deleting!";
                return NotFound();
            }
            _appType.Remove(obj); // So this Removes the database.
            _appType.Save(); // But this is what actually saves it?!?

                TempData[WebConstance.Success] = "Deleted successfully!";
            return RedirectToAction("Index"); // We're in the same controller we don't need to define controller name here
        }
    }
}

ecommerce-masonry/ecommerce-masonry/Views/ApplicationType/Create.cshtml
@model Masonry_Models.ApplicationType


<form method="post" asp-action="Create">
    @*We can delete this "asp-action="Create"". It's optional' because we are in Create post action and it is the same name as Create*@

    <div class="border p-3 bg-white">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row py-2">
            <h2 class="text-info pl-3"> Create Application Type</h2>
            <div class="row">
                <div class="col-8">
                    <div class="form-group row py-2">
                        <div class="col-4">
                            <label asp-for="CategoryName"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="CategoryName" class="form-control" />
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>

                    </div>

                    <div class="form-group row py-2">
                        <div class="col-8 offset-4 row">

                            <div class="col">
                                @*<input type="submit" class=" btn btn-info w-100" value="Create" />*@
                                <button type="submit" class="btn btn-primary w-100">
                                    <i class="fas fa-plus"></i> &nbsp; Create
                                </button>
                            </div>
                            <div class="col">
                                <a asp-action="Index" class="btn btn-success w-100">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    @* Keep this empty *@
                </div>
            </div>
        </div>
    </div>
</form>

@*The below section adds the client side validation*@
@section Scripts{

    @{
                        <partial name="_ValidationScriptsPartial" />
    }

}

ecommerce-masonry/ecommerce-masonry/Views/ApplicationType/Delete.cshtml
@model Masonry_Models.ApplicationType


<form method="post" asp-action="DeletePost">
    @*We can delete this "asp-action="DeletePost"". It's optional' because we are in DeletePost post action and it is the same name as DeletePost*@
    <input asp-for="ID" hidden /> @*This solves an error, when we have a complex object in category. Test it.*@
    @*Form executes post method and looks for post action method of "Edit"*@

    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
    <div class="form-group row py-2">
        <h2 class="text-info pl-3"> Delete ApplicationType</h2>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="CategoryName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CategoryName" disabled class="form-control" />
                        @*<span asp-validation-for="CategoryName" class="text-danger"></span>*@
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        @*<label asp-for="DisplayOrder"></label>*@
                    </div>
                    <div class="col-8">
                        @*<input asp-for="DisplayOrder" disabled class="form-control" />*@
                        @*<span asp-validation-for="DisplayOrder" class="text-danger"></span>*@
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            @* <input type="submit" class=" btn btn-danger w-100" value="Delete" />*@
                            <button type="submit" class="btn btn-danger w-100">
                                <i class="fas fa-trash-alt"></i> &nbsp; Delete
                            </button>
                        </div>
                        <div class="col">
                            <a asp-controller="ApplicationType" asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> &nbsp; Back</a>
                            @* If we're using views within same category, asp-controller="category" can be optional'  *@
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
    </div>
</form>

@*The below section adds the client side validation*@
@section Scripts{

    @{
                        <partial name="_ValidationScriptsPartial" />
    }

}

ecommerce-masonry/ecommerce-masonry/Views/ApplicationType/Edit.cshtml
@model Masonry_Models.ApplicationType


<form method="post" asp-action="Edit">
    @*We can delete this "asp-action="Edit"". It's optional' because we are in Edit post action and it is the same name as Edit*@
    <input asp-for="ID" hidden /> @*This solves an error, when we have a complex object in category. Test it.*@
    @*Form executes post method and looks for post action method of "Edit"*@

    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
    <div class="form-group row py-2">
        <h2 class="text-info pl-3"> Edit ApplicationType Name</h2>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="CategoryName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        @*<label asp-for="DisplayOrder"></label>*@
                    </div>
                    <div class="col-8">
                        @*<input asp-for="DisplayOrder" class="form-control" />*@
                        @*<span asp-validation-for="DisplayOrder" class="text-danger"></span>*@
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            @*<input type="submit" class=" btn btn-info w-100" value="Update" />*@
                            <button type="submit" class="btn btn-info w-100">
                                <i class="fas fa-edit"></i> &nbsp; Update
                            </button>
                        </div>
                        <div class="col">
                            <a asp-controller="ApplicationType" asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> &nbsp; Back</a>
                            @* If we're using views within same category, asp-controller="category" can be optional'  *@
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
    </div>
</form>

@*The below section adds the client side validation*@
@section Scripts{

    @{
                        <partial name="_ValidationScriptsPartial" />
    }

}

ecommerce-masonry/ecommerce-masonry/Views/ApplicationType/Index.cshtml
@model IEnumerable<Masonry_Models.ApplicationType>;

<div class="container p-3 bg-white">
    <div class=" row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ApplicationType" asp-action="Create" class=" btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New ApplicationType
            </a>
        </div>
    </div>
    <br />
    <br />

    @if (Model.Count() > 0)
    {
<table class="table table-bordered table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
            </th>

            <th></th>
        </tr>

    </thead>
    <tbody>

        @foreach (var obj in Model)
        {
<tr>
    <td width="50%">@obj.CategoryName</td>
    <td class="text-center">
        @* So, do we use  asp-route-data="@obj.ID" or asp-route-id="@obj.ID" ???*@
        <div class="w-75 btn-group" role="group">
            @*Below is how we access controller and respective action we wish*@
            <a asp-controller="ApplicationType" asp-route-id="@obj.ID" asp-action="Edit" class=" btn btn-primary mx-2">
                @*What controller and what action method?*@
                <i class="fas fa-edit"></i> &nbsp; Edit
            </a>
            @*Below is how we access controller and respective action we wish*@
            <a asp-controller="ApplicationType" asp-route-id="@obj.ID" asp-action="Delete" class=" btn btn-danger mx-2">
                @*What controller and what action method?*@
                <i class="fas fa-trash-alt"></i> &nbsp; Delete
            </a>
        </div>
    </td>
</tr>
}
    </tbody>
</table>}
else
{
<p>No application type available.</p>}
</div>